[book]
authors = ["AUTOR"]
language = "pt"
multilingual = true
src = "src"
title = "TITULO DO SEU LIVRO AQUI"

[output.html]
git-repository-url = "https://github.com/{}/{}"
edit-url-template = "https://github.com/{}/{}/edit/master/pt/src{path}"
additional-css = ["theme/css/style.css"]
cname = "CNAME"

[output.html.search]
limit-results = 20
use-boolean-and = true
boost-title = 2
boost-hierarchy = 2
boost-paragraph = 1
expand = true
heading-split-level = 2